language: php
php:
    - 7.4
    - 8.0

env:
    - COMPOSER_EXTRA_ARGS=""
    - COMPOSER_EXTRA_ARGS="--prefer-stable"
    - COMPOSER_EXTRA_ARGS="--prefer-stable --prefer-lowest"

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer update --no-progress --no-suggest --prefer-dist $COMPOSER_EXTRA_ARGS

script:
    - vendor/bin/tester -s -p php -c tests/php.ini tests/Cases

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Coding Standard
            php: 7.4
            script:
                - vendor/bin/ecs check --no-progress-bar --ansi src tests

        -   stage: PHPStan
            php: 7.4
            script:
                - vendor/bin/phpstan analyse -l 7 -c phpstan.neon src tests

        -   stage: Code Coverage
            php: 7.4
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - composer global require php-coveralls/php-coveralls ^2.1.0
                - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

    allow_failures:
        - stage: Code Coverage
        - php: 8.0

sudo: false

cache:
    directories:
        - .ecs_cache
        - $HOME/.composer/cache

notifications:
    email: false
