language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot

env:
    - COMPOSER_EXTRA_ARGS=""
    - COMPOSER_EXTRA_ARGS="--prefer-stable"
    - COMPOSER_EXTRA_ARGS="--prefer-stable --prefer-lowest"

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer update --no-progress --no-suggest --prefer-dist $COMPOSER_EXTRA_ARGS

script:
    - vendor/bin/tester -s tests

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Coding Standard
            php: 7.3
            install:
                - travis_retry composer create-project --no-dev --no-progress --prefer-dist sunfoxcz/coding-standard:dev-master coding-standard
            script:
                - coding-standard/vendor/bin/ecs check --no-progress-bar src

        -   stage: Code Coverage
            php: 7.3
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - composer global require php-coveralls/php-coveralls ^2.1.0
                - ~/.composer/vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml

    allow_failures:
        - stage: Code Coverage
        - php: 7.4snapshot

sudo: false

cache:
    directories:
        - .ecs_cache
        - $HOME/.composer/cache

notifications:
    email: false
