name: Tests

on:
    - push
    - pull_request

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - 8.0
                    - 8.1

            fail-fast: false

        name: PHP ${{ matrix.php }} tests
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: iconv, json
                  coverage: none

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - run: composer update --no-progress --prefer-dist --prefer-stable
            - run: composer tests
            - if: failure()
              run: for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
              shell: bash

    lowest_dependencies:
        name: Lowest Dependencies
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.0
                  extensions: iconv, json
                  coverage: none

            - name: Get Composer Cache Directory
              id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - run: composer update --no-progress --prefer-dist --prefer-stable --prefer-lowest
            - run: composer tests
            - if: failure()
              run: for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
              shell: bash

    test_coverage:
        name: Tests with code coverage
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.1
                    extensions: iconv, json

            -   name: Get Composer Cache Directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-files-dir)"
            -   uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: ${{ runner.os }}-composer-

            -   run: composer update --no-progress --prefer-dist --prefer-stable
            -   run: composer coverage
            -   if: failure()
                run: for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
                shell: bash

            -   name: "Coveralls.io"
                env:
                    CI_NAME: github
                    CI: true
                    COVERALLS_REPO_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                run: |
                    wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                    php php-coveralls.phar --verbose --config tests/.coveralls.yml
